### PR TITLE
Code Refactor - moving helper functions to separate file

### PR DESCRIPTION
**Pull request by ja-osu**
Starting to work on refactoring the views.py file, found some common functionality and created a separate helper function.  I created a separate utils.py file that will store the helper functions.

### CODE REVIEW

**Review by bionfinc — CHANGES_REQUESTED** [review]
This might seem like a nitpick, but per PEP8 code guidelines:
Python functions should have 2 blank lines before them: https://www.python.org/dev/peps/pep-0008/#blank-lines
Function/variable names should be all lowercase with underscores between words: https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

**Comment by ja-osu** [comment]
I updated my code to be in line with PEP8, and made another commit.

**Review by bionfinc — CHANGES_REQUESTED** [review]
- Import statement is still referring to getInfo rather than get_info
- It isn't recommended to use an equality operator against None since that can break in some cases, it's recommended to use `is not` (lines 34 and 119)

**Comment by ja-osu** [comment]
Fixed the wrong import name, and updated the code to use is not.

**Review by bionfinc — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
