### PR TITLE
Added back button to detail view and corrected task/sessions display

### PR DESCRIPTION
**Pull request by ckuchman**
Made the tables only show tasks/sessions for the current user. Added back button, still want to add more to those pages. Tried to clean up the action buttons a bit as well.

### CODE REVIEW

**Comment by adorgan** [comment]
I like the addition of the back button. The only thing I would change is to remove the 'btn-info' class from each button because I noticed a bluish color when the buttons were pressed. Otherwise, the tables are looking nice and clean!

**Review by adorgan — COMMENTED** [review]
I like the addition of the back button. The only thing I would change is to remove the 'btn-info' class from each button because I noticed a bluish color when the buttons were pressed. Otherwise, the tables are looking nice and clean!

**Comment by ckuchman** [comment]
> I like the addition of the back button. The only thing I would change is to remove the 'btn-info' class from each button because I noticed a bluish color when the buttons were pressed. Otherwise, the tables are looking nice and clean!

I tried removing the btn-info and it did not seem to edit that part. Looking at the search button it looks like it might do the same?

**Comment by adorgan** [comment]
> > I like the addition of the back button. The only thing I would change is to remove the 'btn-info' class from each button because I noticed a bluish color when the buttons were pressed. Otherwise, the tables are looking nice and clean!
> 
> I tried removing the btn-info and it did not seem to edit that part. Looking at the search button it looks like it might do the same?

True, the search button has a faint bluish halo around the border when clicked, but with btn-info the back buttons turn blue if you click/hold. Not a big deal, just an annoying bootstrap quirk.

**Review by adorgan — APPROVED** [review]

**Pull request merged**
